# Generated by Django 5.1.3 on 2025-01-23 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Registration', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student_data',
            name='Phone',
            field=models.IntegerField(default=22222),
            preserve_default=False,
        ),
    ]
